version: '3.8'

services:
  api:
    build: .
    container_name: contenedor-api
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/tfg
      SPRING_DATASOURCE_USERNAME: root
      SPRING.DATASOURCE.PASSWORD:

  mariadb:
    image: mariadb:11
    container_name: contenedor-mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: tfg
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
